CREATE TABLE users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(30) NOT NULL,
  pwd VARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL,
  created_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);